"""add job scoring fields for csv import

Revision ID: 075bcd097cda
Revises: 44e8ee387466
Create Date: 2026-08-11 15:14:25.084641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075bcd097cda'
down_revision: Union[str, Sequence[str], None] = '44e8ee387466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('matched', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gaps', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('strengths', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('scored_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('jd_text', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('jd_text')
        batch_op.drop_column('scored_at')
        batch_op.drop_column('strengths')
        batch_op.drop_column('gaps')
        batch_op.drop_column('matched')
        batch_op.drop_column('summary')
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
