"""add task recurrence fields

Revision ID: 44e8ee387466
Revises: a02a0fb2e30b
Create Date: 2026-07-30 07:38:43.918648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e8ee387466'
down_revision: Union[str, Sequence[str], None] = 'a02a0fb2e30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('repeat_daily', sa.Boolean(), nullable=False, server_default=sa.text('0'))
        )
        batch_op.add_column(sa.Column('repeat_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('series_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_series_id_tasks', 'tasks', ['series_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_series_id_tasks', type_='foreignkey')
        batch_op.drop_column('series_id')
        batch_op.drop_column('repeat_until')
        batch_op.drop_column('repeat_daily')

    # ### end Alembic commands ###
