"""add job resume generation fields

Revision ID: 595d63fb32b0
Revises: 873374f2c98f
Create Date: 2026-08-11 23:19:21.637131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595d63fb32b0'
down_revision: Union[str, Sequence[str], None] = '873374f2c98f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_resume_yaml', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('generated_cover_letter', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resume_generated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('resume_generated_at')
        batch_op.drop_column('generated_cover_letter')
        batch_op.drop_column('generated_resume_yaml')

    # ### end Alembic commands ###
