"""add excluded_recurrence_dates to tasks

Revision ID: 62a75f2e5e6d
Revises: f1e773904c23
Create Date: 2026-08-28 16:21:48.800931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a75f2e5e6d'
down_revision: Union[str, Sequence[str], None] = 'f1e773904c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excluded_recurrence_dates', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('excluded_recurrence_dates')

    # ### end Alembic commands ###
