"""add task reminder fields and push subscriptions

Revision ID: 6d7878153ef0
Revises: c4f97bdb0255
Create Date: 2026-08-19 08:46:22.714934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7878153ef0'
down_revision: Union[str, Sequence[str], None] = 'c4f97bdb0255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remind_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('remind_snooze_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remind_max_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remind_count_sent', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_reminded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('last_reminded_at')
        batch_op.drop_column('remind_count_sent')
        batch_op.drop_column('remind_max_count')
        batch_op.drop_column('remind_snooze_minutes')
        batch_op.drop_column('remind_at')

    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
