"""rename resume_yaml_filename to resume_person_slug

Revision ID: f1e773904c23
Revises: f845cc8a083f
Create Date: 2026-08-20 11:16:40.888831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e773904c23'
down_revision: Union[str, Sequence[str], None] = 'f845cc8a083f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_person_slug', sa.String(), nullable=True))
        batch_op.drop_column('resume_yaml_filename')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_yaml_filename', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('resume_person_slug')

    # ### end Alembic commands ###
