"""add resume_yaml_filename to people

Revision ID: f845cc8a083f
Revises: 6d7878153ef0
Create Date: 2026-08-20 09:59:37.646245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f845cc8a083f'
down_revision: Union[str, Sequence[str], None] = '6d7878153ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_yaml_filename', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('resume_yaml_filename')

    # ### end Alembic commands ###
